.TH BIP 1 "10 October 2005"

.SH NAME

bip \- BIP IRC Proxy

.SH SYNOPSIS

\fBbip\fP [ \fB-f\fP \fIconfig_file\fP ] [ \fB-n\fP ] [ \fB-h\fP ] 

.SH DESCRIPTION

BIP is an IRC Proxy

.SH OPTIONS

.TP
\fB-n\fP
Don't daemonize. Log into stderr.

.TP
\fB-f\fP config_file
Use config_file as the configuration file. 
If no config file is given, bip will try to open ~/.bip/bip.conf.

.TP
\fB-s\fP homedir
Set bip home directory to homedir instead of $HOME/.bip.

.TP
\fB-h\fP
Help.

.SH SEE ALSO

bip.conf

.SH AUTHOR

Arnaud 'nohar' Cornet
Loic 'Kyoshiro' Gomez

Thanks to jj, YS and lafouine, for hanging around while we were coding.

Crypto shamelessly taken from Christophe 'sexy' Devine.

