.TH BIPMKPW 1 "6 July 2005"

.SH NAME

bipmkpw \- Password hasher for BIP

.SH SYNOPSIS

\fBbipmkpw\fP

.SH DESCRIPTION

bipmkpw converts a password into the double-hash used by bip. Copy the
generated output from bipmkpw into bip config file.

.SH SEE ALSO

bip.conf

.SH COPYRIGHT

Arnaud 'nohar' Cornet
Loïc 'Kyoshiro' Gomez

Thanks to jj, YS and lafouine, for hanging around while we were coding.

Crypto shamelessly taken from Christophe 'sexy' Devine.

