#!/bin/sh

set -e

prefix=bip-$(date +%y%m%d)

if [ ! -d src ] ; then
	echo "Please run me in bip sources root." >&2 
	exit 1
fi

git-archive --format=tar --prefix=$prefix/ HEAD | gzip -c > ../$prefix.tar.gz

