#define DEFAULT_LEX_BACKLOG 1
#define DEFAULT_LEX_ALWAYS_BACKLOG 0
#define DEFAULT_LEX_BL_MSG_ONLY 0
#define DEFAULT_LEX_BACKLOG_LINES 10
#define DEFAULT_LEX_BACKLOG_NO_TIMESTAMP 0
#define DEFAULT_LEX_BLRESET_ON_TALK 0
